// <auto-generated />
using System;
using Examcy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examcy.Migrations
{
//    [DbContext(typeof(AppDBContent))]
//    partial class AppDBContentModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.4")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("Examcy.Data.Models.AchievementsList", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Img")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("MaxCount")
//                        .HasColumnType("int");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("achivementsList");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Answers", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Answer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("StudentId");

//                    b.HasIndex("TaskId");

//                    b.ToTable("answers");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.AssignedTasks", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("StudentId");

//                    b.HasIndex("TaskId");

//                    b.ToTable("assignedTasks");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.AssignedVars", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime>("DateTime")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("Result")
//                        .HasColumnType("int");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.Property<int>("VarId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("StudentId");

//                    b.HasIndex("VarId");

//                    b.ToTable("assignedVars");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Course", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsOpen")
//                        .HasColumnType("bit");

//                    b.Property<int>("ModelEGR")
//                        .HasColumnType("int");

//                    b.Property<int>("ModelId")
//                        .HasColumnType("int");

//                    b.Property<int>("TeacherId")
//                        .HasColumnType("int");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("ModelId");

//                    b.HasIndex("TeacherId");

//                    b.ToTable("courses");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Group", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("groups");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.GroupCourse", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("CourseId")
//                        .HasColumnType("int");

//                    b.Property<int>("GroupId")
//                        .HasColumnType("int");

//                    b.Property<bool>("IsCommonGroup")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.HasIndex("CourseId");

//                    b.HasIndex("GroupId");

//                    b.ToTable("groupCourses");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.ModelsOfEGE", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("models");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Sessions", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("IdSession")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("IdUser")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("sessions");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SetTasks", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("SetId")
//                        .HasColumnType("int");

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("TaskId");

//                    b.ToTable("setTasks");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SetTasksAnswer", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Answer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("SetId")
//                        .HasColumnType("int");

//                    b.Property<int>("SetTasksId")
//                        .HasColumnType("int");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("SetTasksId");

//                    b.HasIndex("StudentId");

//                    b.ToTable("setTasksAnswers");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SolvedTaskInVar", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Answer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("AssignedVarId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("AssignedVarId");

//                    b.HasIndex("TaskId");

//                    b.ToTable("solvedTaskInVars");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Student", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Img")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("LastDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("UserId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("student");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentAchievements", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("AchievementsListId")
//                        .HasColumnType("int");

//                    b.Property<int>("Count")
//                        .HasColumnType("int");

//                    b.Property<int>("IdAchive")
//                        .HasColumnType("int");

//                    b.Property<int>("IdStudent")
//                        .HasColumnType("int");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("AchievementsListId");

//                    b.HasIndex("StudentId");

//                    b.ToTable("studentAchievements");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentGroup", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("GroupId")
//                        .HasColumnType("int");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("GroupId");

//                    b.HasIndex("StudentId");

//                    b.ToTable("studentGroups");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentVar", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime>("DateTime")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("StudentId")
//                        .HasColumnType("int");

//                    b.Property<int>("VarId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("StudentId");

//                    b.HasIndex("VarId");

//                    b.ToTable("studentVars");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Task", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Answer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsTesttask")
//                        .HasColumnType("bit");

//                    b.Property<int>("TaskTypeId")
//                        .HasColumnType("int");

//                    b.Property<string>("Text")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Type")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("TaskTypeId");

//                    b.ToTable("tasks");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.TaskInVar", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.Property<int>("VarId")
//                        .HasColumnType("int");

//                    b.Property<int>("numberTaskInVar")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("TaskId");

//                    b.HasIndex("VarId");

//                    b.ToTable("taskInVar");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.TaskType", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("NumTypeEGE")
//                        .HasColumnType("int");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("taskTypes");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.TaskTypeModel", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("ModelId")
//                        .HasColumnType("int");

//                    b.Property<int>("ModelsOfEGEId")
//                        .HasColumnType("int");

//                    b.Property<int>("TaskTypeId")
//                        .HasColumnType("int");

//                    b.Property<int>("TypeId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("ModelsOfEGEId");

//                    b.HasIndex("TaskTypeId");

//                    b.ToTable("taskTypeModels");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Teacher", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("IdUser")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("LastDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("teachers");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Theme", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("CourseId")
//                        .HasColumnType("int");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("CourseId");

//                    b.ToTable("themes");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.ThemeTask", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("TaskId")
//                        .HasColumnType("int");

//                    b.Property<int>("ThemeId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("TaskId");

//                    b.HasIndex("ThemeId");

//                    b.ToTable("themeTasks");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Theory", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Text")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("ThemeId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("ThemeId");

//                    b.ToTable("theories");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.User", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Login")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("RoleId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("users");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.UserRole", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("userRoles");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Var", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("CourseId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("CourseId");

//                    b.ToTable("vars");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Answers", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Student");

//                    b.Navigation("Task");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.AssignedTasks", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Student");

//                    b.Navigation("Task");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.AssignedVars", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Var", "Var")
//                        .WithMany()
//                        .HasForeignKey("VarId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Student");

//                    b.Navigation("Var");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Course", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.ModelsOfEGE", "Model")
//                        .WithMany()
//                        .HasForeignKey("ModelId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Teacher", "Teacher")
//                        .WithMany()
//                        .HasForeignKey("TeacherId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Model");

//                    b.Navigation("Teacher");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.GroupCourse", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Course", "Course")
//                        .WithMany()
//                        .HasForeignKey("CourseId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Group", "Group")
//                        .WithMany()
//                        .HasForeignKey("GroupId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Course");

//                    b.Navigation("Group");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SetTasks", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Task");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SetTasksAnswer", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.SetTasks", "SetTasks")
//                        .WithMany()
//                        .HasForeignKey("SetTasksId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("SetTasks");

//                    b.Navigation("Student");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.SolvedTaskInVar", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.AssignedVars", "AssignedVar")
//                        .WithMany()
//                        .HasForeignKey("AssignedVarId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("AssignedVar");

//                    b.Navigation("Task");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Student", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.User", "User")
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentAchievements", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.AchievementsList", "AchievementsList")
//                        .WithMany()
//                        .HasForeignKey("AchievementsListId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("AchievementsList");

//                    b.Navigation("Student");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentGroup", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Group", "Group")
//                        .WithMany()
//                        .HasForeignKey("GroupId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Group");

//                    b.Navigation("Student");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.StudentVar", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Student", "Student")
//                        .WithMany()
//                        .HasForeignKey("StudentId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Var", "Var")
//                        .WithMany()
//                        .HasForeignKey("VarId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Student");

//                    b.Navigation("Var");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Task", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.TaskType", "TaskType")
//                        .WithMany()
//                        .HasForeignKey("TaskTypeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("TaskType");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.TaskInVar", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Var", "Var")
//                        .WithMany()
//                        .HasForeignKey("VarId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Task");

//                    b.Navigation("Var");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.TaskTypeModel", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.ModelsOfEGE", "ModelsOfEGE")
//                        .WithMany()
//                        .HasForeignKey("ModelsOfEGEId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.TaskType", "TaskType")
//                        .WithMany()
//                        .HasForeignKey("TaskTypeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("ModelsOfEGE");

//                    b.Navigation("TaskType");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Theme", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Course", "Course")
//                        .WithMany()
//                        .HasForeignKey("CourseId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Course");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.ThemeTask", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Task", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Examcy.Data.Models.Theme", "Theme")
//                        .WithMany()
//                        .HasForeignKey("ThemeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Task");

//                    b.Navigation("Theme");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Theory", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Theme", "Theme")
//                        .WithMany()
//                        .HasForeignKey("ThemeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Theme");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.User", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.UserRole", "Role")
//                        .WithMany("Users")
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Role");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.Var", b =>
//                {
//                    b.HasOne("Examcy.Data.Models.Course", "Course")
//                        .WithMany()
//                        .HasForeignKey("CourseId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Course");
//                });

//            modelBuilder.Entity("Examcy.Data.Models.UserRole", b =>
//                {
//                    b.Navigation("Users");
//                });
//#pragma warning restore 612, 618
//        }
//    }
}
